<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * to get all companys
     * @author Ola
     * @param int $companyId
     */
    public function getAllCompanys(){
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT c.id, c.name
            FROM ObjectsInternJumpBundle:Company c
            ');
        return $query->getResult();
    }
}