<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository {

    /**
     * get the industry companies
     * the main use in CompanyController:industryCompaniesAction
     * @author Mahmoud
     * @param integer $industryId
     * @param integer $orderBy
     * @param integer $orderDirection
     * @param integer $page
     * @param integer $maxResults
     * @return array the count index contains the count of returned objects, the entities index contains the objects
     */
    public function getIndustryCompanies($industryId, $orderBy, $orderDirection, $page = 1, $maxResults = 10) {
        $data = array(
            'count' => 0,
            'enities' => array()
        );
        if ($page >= 1) {
            $page--;
            $mainQuery = '
                FROM ObjectsInternJumpBundle:Company c
                JOIN c.professions p
                WHERE p.id = :industryId
                AND c.locked = 0
                AND c.enabled = 1';
            $parameters = array('industryId' => $industryId);
            $query = $this->getEntityManager()->createQuery("SELECT c $mainQuery ORDER BY c." . $orderBy . " $orderDirection")->setParameters($parameters);
            $countQuery = $this->getEntityManager()->createQuery("SELECT COUNT(c.id) $mainQuery")->setParameters($parameters);
            $query->setFirstResult($page * $maxResults);
            $query->setMaxResults($maxResults);
            $result = $countQuery->getResult();
            $data['count'] = $result[0][1];
            $data['entities'] = $query->getResult();
        }
        return $data;
    }

    /**
     * to get all companys
     * @author Ola
     * @param int $companyId
     */
    public function getAllCompanys() {
        $query = $this->getEntityManager()
                ->createQuery('
            SELECT c.id, c.name
            FROM ObjectsInternJumpBundle:Company c
            WHERE c.locked = 0
            AND c.enabled = 1
            ');
        return $query->getResult();
    }

}