<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewRepository extends EntityRepository
{
    /**
     * This is to get all user's All [upcoming] interviews
     * @param type $uid
     * @return array of interviews
     */
    public function getUpComingInterviews($uid)
    {
            $query = $this->getEntityManager()->createQuery("
            SELECT i
            FROM ObjectsInternJumpBundle:Interview i
            WHERE i.user = :userid
            ")->setParameters(array('userid' => $uid));
        return $query->getResult();
    }
}