parameters:
  loginFormName: 'Login Here'
  loginFormDesc: 'Description Here!'
  studentSignUp_FormName: 'Students SignUp'
  studentSignUp_FormDesc: 'Description Here!'
  studentSignUpEducation_FormName: 'Education Level'
  studentSignUpEducation_FormDesc: 'Description Here!'
  studentSignUpCv_FormName: 'Create your first'
  studentSignUpCv_FormName1: Resume
  studentSignUpCv_FormDesc: 'Description Here!'
  studentSignUpCvSkills_FormName: 'Add skills'
  studentSignUpCvSkills_FormDesc: 'Description Here!'
  studentSignUpCvExperience_FormName: 'Your Experience'
  studentSignUpCvExperience_FormDesc: 'Description Here!'
  studentSignUpCvSuccess_FormName: 'Congratulations on your first resume with InternJump'
  studentSignUpCvSuccess_FormDesc: 'You are just a step away from securing a killer internship'
  studentEditAccount_FormName: 'Edit Account'
  studentEditAccount_FormDesc: 'Description Here!'
  studentEditResume_FormName: 'Update Resume'
  studentEditResume_FormDesc: 'Description Here!'
  studentEditResumeEmpHistory_FormName: 'Add Employment History to Resume'
  studentEditResumeEmpHistory_FormDesc: 'Description Here!'
  studentEditCvAddSkill_FormName: 'Add skills to Resume'
  studentEditCvAddSkill_FormDesc: 'Description Here!'
  studentEditSkill_FormName: 'Edit Skills'
  studentEditSkill_FormDesc: 'Description Here!'
  studentEditEducation_FormName: 'Edit Education'
  studentEditEducation_FormDesc: 'Description Here!'
  studentEditEmpHistory_FormName: 'Edit Employment History'
  studentEditEmpHistory_FormDesc: 'Description Here!'
  studentAddResume_FormName: 'Add Resume'
  studentAddResume_FormDesc: 'Description Here!'
  studentAddEducation_FormName: 'New Education'
  studentAddEducation_FormDesc: 'Description Here!'
  studentAddEmpHistory_FormName: 'New Employment History'
  studentAddEmpHistory_FormDesc: 'Description Here!'
  companySignUp_FormName: 'Employers Signup'
  companySignUp_FormDesc: 'Description Here!'
  companyAddTask_FormName: 'Manage Tasks'
  companyAddTask_FormName1: 'Add Task'
  companyAddTask_FormDesc: 'Description Here!'
  companyAddJob_FormName: 'Add job1'
  companyAddJob_FormDesc: 'Description Here!'
  companyEditTask_FormName: 'Manage Tasks'
  companyEditTask_FormName1: 'Edit Task'
  companyEditTask_FormDesc: 'Description Here!'
  companyEditJob_FormName: 'Edit a job'
  companyEditJob_FormDesc: 'Description Here!'
