ObjectsInternJumpBundle_internship:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/internship.yml"
    prefix:   /internship

ObjectsInternJumpBundle_skill:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/skill.yml"
    prefix:   /skill

ObjectsInternJumpBundle_internJumpUser:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/internJumpUser.yml"
    prefix:   /internJumpUser

ObjectsInternJumpBundle_company:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/company.yml"
    prefix:   /company

company_message:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/company_message.yml"
    prefix:   /company/messages

user_message:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/user_message.yml"
    prefix:   /user/messages

ObjectsInternJumpBundle_education:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/education.yml"
    prefix:   /education

ObjectsInternJumpBundle_cv:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/cv.yml"
    prefix:   /cv

ObjectsInternJumpBundle_employmenthistory:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/employmenthistory.yml"
    prefix:   /employmenthistory

ObjectsInternJumpBundle_test:
    pattern:  /test/
    defaults: { _controller: ObjectsInternJumpBundle:Default:test }

site_homepage:
    pattern:  /
    defaults: { _controller: ObjectsInternJumpBundle:Internjump:homePage }

signup_education:
    pattern:  /user/signup/third/step
    defaults: { _controller: "ObjectsInternJumpBundle:Education:signupEducation" }

signup_cv_skills:
    pattern:  /cv/second/step
    defaults: { _controller: "ObjectsInternJumpBundle:Skill:signupCVSkills" }

signup_cv_experience:
    pattern:  /cv/third/step
    defaults: { _controller: "ObjectsInternJumpBundle:EmploymentHistory:signupCVExperience" }

company_search_for_cv:
    pattern:  /search-for-cv
    defaults: { _controller: "ObjectsInternJumpBundle:Company:searchForCV" }

ObjectsInternJumpBundle_task:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing/task.yml"
    prefix:   /task

student_task:
    pattern:  /userPortal/{loginName}/{status}/{page}/{itemsPerPage}
    defaults: { _controller: "ObjectsInternJumpBundle:Task:studentAllTasks", itemsPerPage: ~, status: all, page: 1 }

employers_data:
    pattern:  /employers_data
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:employersData" }

students_data:
    pattern:  /students_data
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:studentsData" }

privacy:
    pattern:  /privacy
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:privacy" }

termsOfUse:
    pattern:  /terms-of-use
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:termsOfUse" }

aboutUs:
    pattern:  /about-us
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:aboutUs" }
    
contactUs:
    pattern:  /contact-us
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:ContactUs" }

FAQ_page:
    pattern:  /FAQ
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:FAQ" }
    
schools:
    pattern:  /schools
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:schools" }
 
resources:
    pattern:  /Resources/{page}
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:AllResources", page: 1 }
    
show_resources:
    pattern:  /Resource/{id}
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:showOneResource" }
    
    
campus_resps:
    pattern:  /CampusReps
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:campusReps" }  
    
    
mail_404:
    pattern:  /errorEmail
    defaults: { _controller: "ObjectsInternJumpBundle:Internjump:errorPage404Mail" }  
  