add_user_question:
    pattern:  /add_user_question/{userLoginName}/{question}
    defaults: { _controller: "ObjectsInternJumpBundle:Company:addUserQuestion" }
    
add_user_interest:
    pattern:  /add_user_interest/{loginName}/{cvId}
    defaults: { _controller: "ObjectsInternJumpBundle:Company:addUserInterest" }    
    requirements:
        cvId:  \d+
        
company_hire_user:
    pattern:  /company_hire_user/{userId}/{cvId}
    defaults: { _controller: "ObjectsInternJumpBundle:Company:companyHireUser" }
    requirements:
        userId:  \d+
        cvId:  \d+
        
interview_request:
    pattern:  /interview_request/{userId}/{cvId}
    defaults: { _controller: "ObjectsInternJumpBundle:Company:interviewRequest" }
    requirements:
        userId:  \d+
        cvId:  \d+
        
company_notification:
    pattern:  /notification/{type}/{page}/{itemsPerPage}
    defaults: { _controller: "ObjectsInternJumpBundle:Company:companyNotification" , type : all, page : 1, itemsPerPage: ~}  
    
company_notification_mardAs_read:
    pattern:  /company_notification_mardAs_read/{notificationId}
    defaults: { _controller: "ObjectsInternJumpBundle:Company:companyNotificationMardAsRead" }    
    requirements:
        notificationId:  \d+
        
company_markAll_notifications_asRead:
    pattern:  /company_markAll_notifications_asRead
    defaults: { _controller: "ObjectsInternJumpBundle:Company:companyMarkAllNotificationsAsRead" }    
    
question_show:
    pattern:  /question/{questionId}/show
    defaults: { _controller: "ObjectsInternJumpBundle:Company:questionShow" }    
    requirements:
        questionId:  \d+    
        
interview_show:
    pattern:  /interview/{interviewId}/show
    defaults: { _controller: "ObjectsInternJumpBundle:Company:interviewShow" }    
    requirements:
        interviewId:  \d+     
        
company_signup:
    pattern:  /signup
    defaults: { _controller: "ObjectsInternJumpBundle:Company:companySignup" }        
    
company_active:
    pattern: /auth/active/{confirmationCode}
    defaults: { _controller: ObjectsInternJumpBundle:Company:activation }    
    
company_edit:
    pattern: /auth/edit
    defaults: { _controller: ObjectsInternJumpBundle:Company:companyEdit }    
    
company_forgot_password:
    pattern: /forgot/password
    defaults: { _controller: ObjectsInternJumpBundle:Company:companyForgotPassword }
    
company_change_password:
    pattern: /change/password/{confirmationCode}/{email}
    defaults: { _controller: ObjectsInternJumpBundle:Company:companyChangePassword } 
    
get_company_notifications:
    pattern: /get_company_notifications
    defaults: { _controller: ObjectsInternJumpBundle:Company:getCompanyNotifications }     
    
add_interest:
    pattern: /add_interest/{loginName}/{cvId}
    defaults: { _controller: ObjectsInternJumpBundle:Company:addInterest }      